syntax enable

" Stop acting like classic vi
set nocompatible		" disable vi compability mode
set noswapfile			" don't create swapfiles
set nobackup			" don't backup, use git!

" Enable filetype
filetype plugin indent on

" Persist undo history between file editing sessions.
set undofile
set undodir=~/.vim/undodir

" Modify indenting settings
set autoindent			" autoindent always ON

" Modify some other settingns about files
set encoding=utf8		" autoindent use unicode
set backspace=indent,eol,start	" backspace always works on insert mode
set hidden

set noshowmode
set laststatus=1 		" always show statusbar
set wildmenu			" enable visual wildmenu

set nowrap			" don't wrap long lines
set number			" show line numbers
set rnu				" show numbers as relative by default
set showmatch			" highlight matching parentheses and brackets

set noerrorbells
set ruler
set incsearch

set showcmd  		        " show vim commands in normal mode
set colorcolumn=80

command! W execute 'w !sudo tee % > /dev/null' <bar> edit!


call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'gruvbox-community/gruvbox'
"Plug 'arcticicestudio/nord-vim'
Plug 'michaeljsmith/vim-indent-object'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-endwise'
Plug 'ap/vim-css-color'
Plug 'lifepillar/pgsql.vim'

call plug#end()

"colorscheme nord
colorscheme gruvbox
let g:airline_powerline_fonts=1
set background=dark
"let g:airline_statusline_ontop=1

hi Normal guibg=NONE ctermbg=NONE
" Mark trailing spaces depending on whether we have a fancy terminal or not
if &t_Co > 2
	highlight ExtraWhitespace ctermbg=88 guibg=#fb4934
	match ExtraWhitespace /\s\+$/
else
	set listchars=trail:~
	set list
endif


let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
let mapleader=" "

noremap <leader>f :Files<cr>
noremap <leader>w :w<cr>
nmap <F5> :set invrelativenumber<CR>

autocmd BufWritePre * %s/\s\+$//e
