syntax enable

" Enable filetype {
filetype plugin indent on
" }

" no compatible for vim-polyglot
set nocompatible		" disable vi compability mode

" Persist undo history between file editing sessions.
set undofile
set undodir=~/.vim/undodir
set noswapfile			" don't create swapfiles
set nobackup			" don't backup, use git!

" Modify indenting settings
set autoindent			" autoindent always ON

" Modify some other settingns about files
set encoding=utf8		" autoindent use unicode
set backspace=indent,eol,start	" backspace always works on insert mode
set hidden

set noshowmode
set laststatus=1 		" always show statusbar
set wildmenu			" enable visual wildmenu
set wildoptions=pum " List options in menu like a popup

set nowrap			" don't wrap long lines
set number			" show line numbers
set rnu				" show numbers as relative by default
set showmatch			" highlight matching parentheses and brackets

set noerrorbells
set ruler
set incsearch

set showcmd  		        " show vim commands in normal mode
set colorcolumn=80
set signcolumn=yes

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'michaeljsmith/vim-indent-object'
Plug 'ryanoasis/vim-devicons'
Plug 'szw/vim-maximizer'

" Syntax highlight
Plug 'sheerun/vim-polyglot'
Plug 'ap/vim-css-color'

" Themes
Plug 'gruvbox-community/gruvbox'

" Async Lint
Plug 'dense-analysis/ale'

" Typing
Plug 'jiangmiao/auto-pairs'
Plug 'alvan/vim-closetag'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'

" Like IDE
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'yggdroot/indentline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'

call plug#end()

" Colorscheme
colorscheme gruvbox

hi Normal guibg=NONE ctermbg=NONE
" Mark trailing spaces depending on whether we have a fancy terminal or not
if &t_Co > 2
	highlight ExtraWhitespace ctermbg=88 guibg=#fb4934
	match ExtraWhitespace /\s\+$/
else
	set listchars=trail:~
	set list
endif

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
set path =.,**
let mapleader=" "

" Search and result center my screen
nmap n nzzzv
nmap N nzzzv

" Moving text
vmap J :m '>+1'<CR>gv=gv
vmap K :m '<-2'<CR>gv=gv
imap <C-j> <esc>:m .+1<CR>==
imap <C-k> <esc>:m .-2<CR>==
nmap <leader>k :m .-2<CR>==
nmap <leader>j :m .+1<CR>==

" Move to buffer with two keys
map <leader>bn :bn<CR>
map <leader>bp :bp<CR>
map <leader>bd :bd<CR>
map <leader>b# :b#<CR>

" Split
map <leader>vs :vsp<CR>
map <leader>hs :sp<CR>

" Resizing Toggle
nmap <leader>ms :MaximizerToggle<CR>
nmap <leader>> 10<C-w>>
nmap <leader>< 10<C-w><
nmap <leader>es <C-w>o

" Change to relative number <-> number
nmap <F5> :set invrelativenumber<CR>

" Save and quit faster
nmap <leader>w :w<CR>
nmap <leader>q :q<CR>
nmap <leader>wq :wq<CR>
nmap <leader>Q :q!<CR>

"I'm no sure this is forever
nnoremap Y y$

" Remove whitespace after save
autocmd BufWritePre * %s/\s\+$//e

" Command to save with file is readonly
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
